[lint]
# Ignore specific error codes for specific files
[lint.per-file-ignores]
"agentical/llm/anthropic/anthropic_chat.py" = ["PLR0912"]  # Too many branches
"agentical/llm/gemini/schema_adapter.py" = ["PLR0912"]  # Too many branches
"agentical/chat_client.py" = ["PLR0915"]  # Too many statements
"tests/*" = ["F841"]  # Ignore unused variables in test files

[lint.pylint]
max-branches = 14  # Default is 12
max-statements = 51  # Default is 50

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.per-file-ignores]
"agentical/llm/anthropic/anthropic_chat.py" = ["PLR0912"]  # Too many branches
"agentical/llm/gemini/schema_adapter.py" = ["PLR0912"]  # Too many branches